repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=--recursive
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--recursive
          - --args=--module
      - id: terraform_docs
        args:
          - "--args=--lockfile=false"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.12.0
    hooks:
      - id: trivyfs-docker
        args:
          - --skip-dirs
          - ./tests
          - . # last arg indicates the path/file to scan
