services:
  gcp-training-ci:
    user: "${USER}"
    image: iktos-gitlab-runner
    build:
      context: .
      args:
        USER: "${USER:-non-root}"
        UID: "${UID:-1000}"
    working_dir: /workdir
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/${USER}/.config/gcloud/application_default_credentials.json
      AUTOAPPROVE: "${AUTOAPPROVE:-0}"
    volumes:
      - .:/workdir:rw
      - ~/.config/gcloud:/home/${USER}/.config/gcloud:rw
      - /tmp/trivy:/tmp/trivy:rw
    entrypoint: task
