services:
  gcp-training-ci:
    user: "${USER}"
    image: iktos-gitlab-runner
    build:
      context: .
      args:
        USER: "${USER:-non-root}"
        UID: "${UID:-1000}"
    working_dir: /workdir
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/${USER}/.config/gcloud/application_default_credentials.json
      CLOUDSDK_CORE_PROJECT: "${TF_VAR_gcp_project_id}"
      AUTOAPPROVE: "${AUTOAPPROVE:-0}"
      NOINIT: "${NOINIT:-0}"
      INFRACOST_API_KEY: "${INFRACOST_API_KEY:-null}"
      IAC_BUCKET: "${INFRA_BUCKET:-null}"
    env_file:
      - ./.env
    volumes:
      - .:/workdir:rw
      - ~/.config/gcloud:/home/${USER}/.config/gcloud:rw
      - /tmp/trivy:/tmp/trivy:rw
    entrypoint: task
