---
version: "3"

silent: true

tasks:
  deploy:
    desc: Deploys the stack
    dotenv: [".env"]
    cmds:
      - task: trivy-fs-scan
      - task: init
      - task: validate
      - task: plan
      - task: trivy-tf-scan
      - task: apply
    preconditions:
      - sh: "gcloud compute regions list"
        msg: "No GCloud authentication credentials found. Cancelling task."

  destroy:
    desc: Destroys the stack
    cmds:
      - task: trivy-fs-scan
      - task: init
      - task: validate
      - task: plan
      - task: trivy-tf-scan
      - task: apply-destroy
    preconditions:
      - sh: "gcloud compute regions list"
        msg: "No GCloud authentication credentials found. Cancelling task."

  trivy-fs-scan:
    dotenv: [".env"]
    cmds:
      - trivy fs --cache-dir /tmp/trivy/ .

  trivy-tf-scan:
    dotenv: [".env"]
    cmds:
      - trivy conf --cache-dir /tmp/trivy/ tfplan

  init:
    dotenv: [".env"]
    cmds:
      - terraform init

  validate:
    cmds:
      - terraform validate

  plan:
    dotenv: [".env"]
    cmds:
      - terraform plan -out tfplan

  apply-destroy:
    dotenv: [".env"]
    cmds:
      - |
        if [[ $AUTOAPPROVE = 1 ]]
        then
          terraform apply -destroy -auto-approve
        else
          terraform apply -destroy
        fi

  apply:
    dotenv: [".env"]
    cmds:
      - |
        if [[ $AUTOAPPROVE = 1 ]]
        then
          terraform apply -auto-approve
        else
          terraform apply
        fi
